# Generated by Django 6.0.6 on 2026-06-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('supervisor', 'Supervisor'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
