# Generated by Django 6.0.6 on 2026-06-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_attachment_type_profile_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='organization_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='organization_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='organization_main_road',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
